### PR TITLE
Update advanced_system_tuning.md

### PR DESCRIPTION
**Pull request by by**
Included disabling of Energy Efficient Ethernet to reduce jitter and lag, made reduction of ethernet coalescence on RX and TX persistent over restarts, and simplified phc2sys.service.

### CODE REVIEW

**Comment by tiagofreire-pt** [comment]
Hi, @by .

Thanks for the PR.

On the Rpi 5B, there is a lack of support to disable EEE and there is event reports of issues with it. https://forums.raspberrypi.com/viewtopic.php?t=360924 I took conservative approach on this, by not including it the command on config.txt file.

About the phy2sys, the tutorial uses it as an internal clock synced source, explicitly. Could you share you vision for the autoconfig flag?

Best regards.

**Comment by by** [comment]
My pleasure, and I'm running kernel 6.9 and do not see any issues with my Ethernet port.
Regarding phc2sys, I would not like to see it doing any direct synchronizations in a single direction but have it decide synchronization direction automagically and run the time via each server's chrony/ntpd/ntpsec for them to manage any adjustments in order to not confuse that algorithm.
Best regards,
        Michael

**Comment by by** [comment]
Apologies, I got carried away: as chronyd/ntpd/ntpsec should consolidate the clock adjustments, phc2sys is not needed at all, instead one would like to add
```
# send to chronyd/ntpd using SHM 2
clock_servo ntpshm
ntpshm_segment 2
```
to `/etc/linuxptp/ptp4l.conf ` to receive the PTP time on SHM 2 (in this case).

**Comment by by** [comment]
The master's `/etc/systemd/system/phc2sys.service` should then have
```
ExecStart=/usr/sbin/phc2sys -c CLOCK_REALTIME -d /dev/pps0 -w -m -u 1024
```
to sync the system clock that's corrected by chrony/ntpd/ntpsec to the hardware clock via phc2sys.

**Comment by by** [comment]
So your suggested approach was best for the master's side, indeed; the client's side should not have phc2sys to not interfere with the system clock from two sides.

**Comment by by** [comment]
I've reworked, expanded and split my point into both server and client side, here, if you are interested: https://github.com/by/ptp4RaspberryPi/blob/main/Setup.md
Thank you very much for your inspiration!

**Pull request closed without merging**
